# Use the official ASP.NET Core runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY NuGetServer/NuGetServer.csproj NuGetServer/
RUN dotnet restore NuGetServer/NuGetServer.csproj

COPY NuGetServer/ NuGetServer/
WORKDIR /src/NuGetServer
RUN dotnet build NuGetServer.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish NuGetServer.csproj -c Release -o /app/publish

# Final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NuGetServer.dll"]
